apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u2631ujpg-python 
  janus-idp.io/tekton: u2631ujpg-python
  backstage.io/kubernetes-id: u2631ujpg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u2631ujpg-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  